---
##################
# Below config params are used to configure contrailctl
# All of below variables are a dict which form individual section of contrailctl/*.conf (controller.conf, agent.conf, etc)
# they are just a dictionary form of config files found under contrailctl/*
# i.e below mentioned global_config is a dictionary form of [GLOBAL] section in contrailct/*.conf - since this is
#      global_config, they are available to all config files
# where control_config is dictionary form of [CONTROL] section in contrailctl/controller.conf
#       webui_config is dictionary form of [WEBUI] section in contrailctl/controller.conf
# for example, if one add configuration  "webui_config: {http_listen_port: 8085}", [WEBUI] section of
# contrailctl/controller.conf will be configured as below - which infact configure webui to listen 8085 for http
#  instead of 8080 which is default
#
# [WEBUI]
# http_listen_port = 8085
#
# REFERENCE: For configuration details, please refer example configurations found in
#  https://github.com/Juniper/contrail-docker/tree/master/tools/python-contrailctl/examples/configs/controller.conf
#
##################

####
# Controller specific config vars - this will be added to contrailctl/controller.conf
####
# controller_config: controller specific global configs - contrailctl/controller.conf will have [GLOBAL] section with
#  configs added in global_config + controller_config
# controller_config: {}

# control_config: config params for control - these will go to [CONTROL] section of contrailctl/controller.conf
# control_config: {}

# dns_config: config params for dns - these will go to [DNS] section of contrailctl/controller.conf
# dns_config: {}

# config_config: config params for config - these will go to [CONFIG] section of contrailctl/controller.conf
# config_config: {}

# configdb_config: config params for configdb - these will go to [CONFIGDB] section of contrailctl/controller.conf
# configdb_config: {}

# api_config: config params for api - these will go to [API] section of contrailctl/controller.conf
# api_config: {}

# schema_config: config params for schema - these will go to [SCHEMA] section of contrailctl/controller.conf
# schema_config: {}

# discovery_config: config params for discovery - these will go to [DISCOVERY] section of contrailctl/controller.conf
# discovery_config: {}

# device_manager_config: config params for device_manager - these will go to [DEVICE_MANAGER] section of contrailctl/controller.conf
# device_manager_config: {}

# svc_monitor_config: config params for svc_monitor - these will go to [SVC_MONITOR] section of contrailctl/controller.conf
# svc_monitor_config: {}

# webui_config: config params for webui - these will go to [WEBUI] section of contrailctl/controller.conf
# webui_config: {}
