---
- name: Configure contrailctl/controller.conf
  ini_file:
    dest: "{{ contrailctl_config_directory }}/controller.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: yes
  with_inidata:
    GLOBAL: "{{ global_config_orig }}"
    CONTROLLER: "{{ controller_config | default({}) }}"
    CONTROL: "{{ control_config | default({}) }}"
    CONFIG: "{{ config_config | default({}) }}"
    DNS: "{{ dns_config | default({}) }}"
    CONFIGDB: "{{ configdb_config | default({}) }}"
    API: "{{ api_config | default({}) }}"
    SCHEMA: "{{ schema_config | default({}) }}"
    DEVICE_MANAGER: "{{ device_manager_config | default({}) }}"
    SVC_MONITOR: "{{ svc_monitor_config | default({}) }}"
    WEBUI: "{{ webui_config_orig | default({}) }}"
    CASSANDRA: "{{ cassandra_config | default({}) }}"
    RABBITMQ: "{{ rabbitmq_config | default({}) }}"
  notify:
    - check controller container
    - contrailctl for controller

- name: Configure contrailctl/controller.conf KEYSTONE section
  ini_file: dest="{{ contrailctl_config_directory }}/controller.conf" section=KEYSTONE option={{ item.key }} value={{ item.value }}  create=yes
  with_dict: "{{ keystone_config | default({}) }}"
  notify:
    - check controller container
    - contrailctl for controller
  when: cloud_orchestrator == "openstack"

- meta: flush_handlers
