---
- name: Configure the /etc/default/neutron-server configuration file with NEUTRON_PLUGIN_CONFIG path
  lineinfile:
    dest: "/etc/default/neutron-server"
    line: 'NEUTRON_PLUGIN_CONFIG=/etc/neutron/plugins/opencontrail/ContrailPlugin.ini'
    state: present
  when: ansible_os_family == 'Debian'
  notify:
    - restart neutron-server for plugin


- name: Configure ContrailPlugin.ini APISERVER section
  ini_file: dest="/etc/neutron/plugins/opencontrail/ContrailPlugin.ini" section=APISERVER option={{ item.key }} value={{ item.value }}  create=yes
  with_dict:
    api_server_ip: "{{ api_server_ip }}"
    api_server_port: "{{ api_server_port }}"
    multi_tenancy: "{{ multi_tenancy }}"
    contrail_extensions: "ipam:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_ipam.NeutronPluginContrailIpam,policy:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_policy.NeutronPluginContrailPolicy,route-table:neutron_plugin_contrail.plugins.opencontrail.contrail_plugin_vpc.NeutronPluginContrailVpc,contrail:None,service-interface:None,vf-binding:None"
  notify:
    - restart neutron-server for plugin


- name: Configure ContrailPlugin.ini KEYSTONE section
  ini_file: dest="/etc/neutron/plugins/opencontrail/ContrailPlugin.ini" section=KEYSTONE option={{ item.key }} value={{ item.value }}  create=yes
  with_dict:
    admin_user: "{{ keystone_admin_user }}"
    admin_password: "{{ keystone_admin_password }}"
    admin_tenant_name: "{{ keystone_admin_tenant }}"
    auth_url: "{{ keystone_auth_protocol }}://{{ keystone_ip }}:{{ keystone_admin_port }}/{{ keystone_version }}"
  notify:
    - restart neutron-server for plugin


- name: Configure neutron.conf service_plugin 
  ini_file: dest="/etc/neutron/neutron.conf" section=DEFAULT option={{ item.key }} value={{ item.value }}  create=yes
  with_dict:
    core_plugin        : "neutron_plugin_contrail.plugins.opencontrail.contrail_plugin.NeutronPluginContrailCoreV2"
    service_plugins    : "neutron_plugin_contrail.plugins.opencontrail.loadbalancer.v2.plugin.LoadBalancerPluginV2"
    api_extensions_path: "extensions:/usr/lib/python2.7/site-packages/neutron_plugin_contrail/extensions:/usr/lib/python2.7/site-packages/neutron_lbaas/extensions"

  notify:
    - restart neutron-server for plugin

- name: Configure neutron.conf service_provider
  ini_file: dest="/etc/neutron/neutron.conf" section=service_providers option={{ item.key }} value={{ item.value }}  create=yes
  with_dict:
    service_provider : "LOADBALANCER:Opencontrail:neutron_plugin_contrail.plugins.opencontrail.loadbalancer.driver.OpencontrailLoadbalancerDriver:default"

  notify:
    - restart neutron-server for plugin
