---
- name: Hack to install ocata nova-compute when running with kolla openstack
  file:
    path: /etc/apt/preferences.d/contrail_repo.pref
    state: absent
  when:
    openstack_sku == 'ocata'

- name: Add ocata repo
  apt_repository:
    repo: 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata main'
  when:
    openstack_sku == 'ocata'

- name: Install nova compute packages
  apt: name={{ item }} state=latest force=yes
  with_items: "{{nova_compute_pkgs}}"
  when: ansible_os_family == 'Debian'

- name: Install nova compute packages
  yum: name={{ item }} state=latest
  with_items: "{{nova_compute_pkgs}}"
  when: ansible_os_family == 'RedHat'

- name: Install DPDK packages, if applicable
  apt: name={{ item }} state=latest force=yes
  when:
    - dpdk_mode == True
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '16.04'
  with_items:
    - contrail-nova-vif

- name: create a symlink from /bin/true to /sbin/chkconfig
  file: src=/bin/true dest=/sbin/chkconfig state=link
  when: ansible_os_family == 'Debian'
