---
contrail_compute_mode: bare_metal
enable_openstack_compute: true
enable_lbaas: true
deployment_platform: docker
no_upstart: "{{ true if deployment_platform == 'docker' }}"
kernel_version_installed: ""
