---
contrail_compute_mode: bare_metal
vcenter_compute_mode: "bare_metal"
enable_openstack_compute: "{{ false if provision_type == 'ISSU' else true }}"
enable_lbaas: true
deployment_platform: docker
no_upstart: "{{ true if deployment_platform == 'docker' }}"
#Tor Agent defaults
tor_agent: {}
tor_agent_list: []
kernel_version_installed: ""
