---
- name: Copy contrail analyticsdb image
  copy:
    src: "{{ docker_image_load_path }}/{{ contrail_analyticsdb_image_archive }}"
    dest: "/tmp/{{ contrail_analyticsdb_image_archive }}"
  when: docker_registry is not defined or load_contrail_analyticsdb_image is defined

- name: "Load contrail analyticsdb image"
  docker_image:
    name: contrail-analyticsdb
    tag: "{{ contrail_version }}"
    load_path: "/tmp/{{ contrail_analyticsdb_image_archive }}"
  when: docker_registry is not defined or load_contrail_analyticsdb_image is defined

- name: Configure contrailctl/analyticsdb.conf
  include: "contrailctl/analyticsdb/{{ contrailctl_config_mode }}.yml"

- name: "Start contrail analyticsdb container"
  docker_container:
    name: analyticsdb
    image: "{{ analyticsdb_image }}"
    privileged: true
    network_mode: host
    state: started
    pull: "{{ always_pull_image }}"
    tty: true
    restart_policy: unless-stopped
    capabilities:
      - AUDIT_WRITE
    volumes:
      - "{{ contrailctl_config_directory }}:/etc/contrailctl/"
