---
- name: Copy contrail kube_manager image
  copy:
    src: "{{ docker_image_load_path }}/{{ contrail_kube_manager_packages }}"
    dest: "/tmp/{{ contrail_kube_manager_image_archive }}"
  when: docker_registry is not defined or load_contrail_kube_manager_image is defined

- name: "Load contrail kube_manager image"
  docker_image:
    name: contrail-kube-manager
    tag: "{{ contrail_version }}"
    load_path: "/tmp/{{ contrail_kube_manager_image_archive }}"
  when: docker_registry is not defined  or load_contrail_kube_manager_image is defined

- name: Configure contrailctl/kubemanager.conf
  include: "contrailctl/kubemanager/{{ contrailctl_config_mode }}.yml"

- name: "Start contrail kube_manager container"
  docker_container:
    name: contrail-kube-manager
    image: "{{ contrail_kube_manager_image }}"
    network_mode: host
    state: started
    privileged: true
    pull: "{{ always_pull_image }}"
    tty: true
    restart_policy: unless-stopped
    restart_retries: 3
    volumes:
      - "{{ contrailctl_config_directory }}:/etc/contrailctl/"
