---
- name: Install cni dependencies
  pip: name="{{ item }}" state=present
  with_items:
    - pyroute2

- name: Install contrail cni package
  package: name="{{ contrail_cni_package_name }}" state=present

- name: Make sure cni directories exist
  file: path="{{ item }}" state=directory recurse=true
  with_items:
    - /var/log/contrail/cni
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Create cni config
  copy: src=kube_cni.conf dest=/etc/cni/net.d/10-contrail.conf

- name: Create softlink contrail cni binary to /opt/cni/bin
  file: src=/usr/bin/contrail-kube-cni  dest=/opt/cni/bin/contrail-kube-cni state=link
  when: cloud_orchestrator != 'mesos'
