---
- name: sm_status_report - lb_started
  debug:
    msg: "lb_started"

- name: Copy contrail lb image
  copy:
    src: "{{ docker_image_load_path }}/{{ contrail_lb_image_archive }}"
    dest: "/tmp/{{ contrail_lb_image_archive }}"
  when: docker_registry is not defined or load_contrail_lb_image is defined

- name: "Load contrail lb image"
  docker_image:
    name: contrail-lb
    tag: "{{ contrail_version }}"
    timeout: "{{ container_image_load_timeout }}"
    load_path: "/tmp/{{ contrail_lb_image_archive }}"
  when: docker_registry is not defined or load_contrail_lb_image is defined

- name: Set haproxy toragent configuration dictionary
  set_fact:
    haproxy_toragent_config: "{{ haproxy_toragent_config|combine( {'haproxy_toragent_config': tor_agent|string} ) }}"
  when: tor_agent is defined

- name: Configure contrailctl/lb.conf
  include: "contrailctl/lb/{{ contrailctl_config_mode }}.yml"

# Copy SSL certs to container
- include: copy_ssl_certs.yml

- name: "Start Loadbalancer container for ubuntu 14.0x"
  docker_container:
    name: lb
    image: "{{ lb_image }}"
    privileged: true
    pid_mode: host
    network_mode: host
    state: started
    tty: true
    pull: "{{ always_pull_image }}"
    restart_policy: unless-stopped
    capabilities:
      - AUDIT_WRITE
    volumes:
      - "{{ contrailctl_config_directory }}:/etc/contrailctl/"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04' and os_release != 'ubuntu16.04'

- name: "Start Loadbalancer container"
  docker_container:
    name: lb
    image: "{{ lb_image }}"
    privileged: true
    network_mode: host
    state: started
    tty: true
    pull: "{{ always_pull_image }}"
    restart_policy: unless-stopped
    capabilities:
      - AUDIT_WRITE
    volumes:
      - "{{ contrailctl_config_directory }}:/etc/contrailctl/"
  when: ansible_distribution_version != '14.04' or os_release == 'ubuntu16.04'

- name: sm_status_report - lb_completed
  debug:
    msg: "lb_completed"
